[book]
authors = [
    "Jack Grigg",
    "Sean Bowe",
    "Daira Hopwood",
    "Ying Tong Lai",
]
language = "en"
multilingual = false
src = "src"
title = "The halo2 Book"

[preprocessor.katex]
macros = "macros.txt"
